import test from 'node:test';import assert from 'node:assert/strict';
import { LruTtlCache } from '../lib/cache.js';
import { scoreEvidence, tokenize, validateEvidence } from '../lib/research.js';

test('LRU cache returns values and evicts oldest',()=>{const c=new LruTtlCache({max:2,ttlMs:10000});c.set('a',1);c.set('b',2);assert.equal(c.get('a'),1);c.set('c',3);assert.equal(c.get('b'),undefined);assert.equal(c.get('a'),1)});
test('in-flight cache deduplicates concurrent work',async()=>{const c=new LruTtlCache();let calls=0;const f=()=>c.getOrCreate('x',async()=>{calls++;await new Promise(r=>setTimeout(r,20));return 42});const [a,b,c2]=await Promise.all([f(),f(),f()]);assert.equal(calls,1);assert.equal(a.value,42);assert.equal(b.value,42);assert.equal(c2.value,42)});
test('research tokenization and morphology rank related evidence',()=>{assert.deepEqual(tokenize("Strategies aren't magic"),['strategies',"aren't",'magic']);const strong=scoreEvidence('trading strategies',{title:'Strategy rules',text:'These trading strategies use entries and exits.'});const weak=scoreEvidence('trading strategies',{title:'Other',text:'Completely unrelated paragraph.'});assert.ok(strong>weak);assert.ok(scoreEvidence('strategy',{title:'Plural',text:'Several strategies are discussed.'})>0);assert.equal(scoreEvidence('AI',{title:'Other',text:'He said this yesterday.'}),0)});
test('evidence validation assigns bounded canonical source labels',()=>{const out=validateEvidence([{videoId:'abcdefghijk',title:'T',url:'https://evil.example/phish',startMs:1200,text:' evidence   text '}]);assert.equal(out[0].label,'S1');assert.equal(out[0].text,'evidence text');assert.equal(out[0].url,'https://www.youtube.com/watch?v=abcdefghijk');assert.throws(()=>validateEvidence([{videoId:'bad',text:'x'}]),/No valid evidence/)});

import { checkpointKey, validateCheckpoint } from '../lib/ai-transcription.js';
test('AI checkpoint keys are deterministic and configuration-sensitive',()=>{const c={model:'m1',chunkSeconds:900,responseFormat:'verbose_json'};assert.equal(checkpointKey('abcdefghijk','en',c),checkpointKey('abcdefghijk','en',c));assert.notEqual(checkpointKey('abcdefghijk','en',c),checkpointKey('abcdefghijk','fr',c));assert.notEqual(checkpointKey('abcdefghijk','en',c),checkpointKey('abcdefghijk','en',{...c,model:'m2'}))});

test('AI checkpoints reject stale provider/config data and sanitize reusable chunks',()=>{const c={apiUrl:'https://provider.example/v1/audio',model:'m1',chunkSeconds:900,responseFormat:'verbose_json'};const raw={version:2,videoId:'abcdefghijk',language:'en',model:'m1',chunkSeconds:900,chunks:[{text:' hello   world ',segments:[{startMs:0,durationMs:1000,text:' hello '}]}],result:null};const ok=validateCheckpoint(raw,{videoId:'abcdefghijk',language:'en',c});assert.equal(ok.chunks[0].text,'hello world');assert.equal(ok.chunks[0].segments[0].text,'hello');assert.equal(validateCheckpoint(raw,{videoId:'abcdefghijk',language:'fr',c}),null);assert.equal(validateCheckpoint({...raw,version:1},{videoId:'abcdefghijk',language:'en',c}),null);assert.notEqual(checkpointKey('abcdefghijk','en',c),checkpointKey('abcdefghijk','en',{...c,apiUrl:'https://other.example/v1/audio'}))});

test('AI checkpoint recovery preserves paid chunk text when timestamp segments are missing',()=>{const c={apiUrl:'https://provider.example/v1/audio',model:'m1',chunkSeconds:900,responseFormat:'verbose_json'};const raw={version:2,videoId:'abcdefghijk',language:'en',model:'m1',chunkSeconds:900,chunks:[{text:'paid words survive',segments:[]}],result:null};const ok=validateCheckpoint(raw,{videoId:'abcdefghijk',language:'en',c});assert.equal(ok.chunks[0].segments.length,1);assert.equal(ok.chunks[0].segments[0].startMs,0);assert.equal(ok.chunks[0].segments[0].durationMs,900000);assert.equal(ok.chunks[0].segments[0].text,'paid words survive')});

test('AI checkpoint validation rejects corrupted chunk and completed-result hashes',()=>{const c={apiUrl:'https://provider.example/v1/audio',model:'m1',chunkSeconds:900,responseFormat:'verbose_json'};const base={version:2,videoId:'abcdefghijk',language:'en',model:'m1',chunkSeconds:900,chunks:[{text:'paid words',textHash:'deadbeef',segments:[{startMs:0,durationMs:1000,text:'paid words'}]}],result:{videoId:'abcdefghijk',source:'ai-transcription',text:'paid words'}};const badChunk=validateCheckpoint(base,{videoId:'abcdefghijk',language:'en',c});assert.equal(badChunk.chunks[0],null);assert.equal(badChunk.result,null);const good={...base,chunks:[{text:'paid words',segments:[{startMs:0,durationMs:1000,text:'paid words'}]}],resultHash:'deadbeef'};const badResult=validateCheckpoint(good,{videoId:'abcdefghijk',language:'en',c});assert.equal(badResult.result,null)});

test('AI checkpoint completed results are reconstructed from sanitized chunks and extra fields are dropped',()=>{const c={apiUrl:'https://provider.example/v1/audio',model:'m1',chunkSeconds:900,responseFormat:'verbose_json'};const raw={version:2,videoId:'abcdefghijk',language:'en',model:'m1',chunkSeconds:900,chunks:[{text:'hello world',segments:[{startMs:0,durationMs:1000,text:'hello world'}]}],result:{videoId:'abcdefghijk',source:'ai-transcription',text:'hello world',language:'en',trackName:'fixture',unexpected:'do-not-return'}};const ok=validateCheckpoint(raw,{videoId:'abcdefghijk',language:'en',c});assert.equal(ok.result.text,'hello world');assert.equal(ok.result.unexpected,undefined);assert.equal(ok.result.providerModel,'m1');assert.deepEqual(ok.result.segments,[{startMs:0,durationMs:1000,text:'hello world'}])});
