import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import { createServer } from '../server.js';

function fakeManager(){const calls=[];const monitor={id:'12345678-abcd',channel:'@fixture',title:'Fixture',enabled:true,status:'success',generation:1,snapshotReady:true};return{calls,startScheduler(){calls.push(['start'])},stopScheduler(){calls.push(['stop'])},status(){return{schedulerEnabled:true,pollSeconds:300,maxVideos:50000}},async list(){calls.push(['list']);return[monitor]},async get(id){return id===monitor.id?monitor:null},async upsert(body){calls.push(['upsert',body]);return{...monitor,...body}},async setEnabled(id,enabled){calls.push(['enabled',id,enabled]);return{...monitor,enabled}},async remove(id){calls.push(['delete',id]);return{ok:true}},async runNow(id){calls.push(['run',id]);return monitor},async *snapshotLines(id){calls.push(['snapshot',id]);yield '{"type":"monitor-snapshot","schema":1}\n';yield '{"type":"end","videos":0,"generation":1,"chain":"x"}\n'}}}
async function withServer(manager,fn){const server=createServer({monitorManager:manager});await new Promise(r=>server.listen(0,'127.0.0.1',r));const {port}=server.address();try{return await fn(port)}finally{await new Promise(r=>server.close(r))}}
function request(port,{method='GET',path='/',headers={},body=''}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,method,path,headers:{Host:`localhost:${port}`,...headers}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks).toString()}))});req.on('error',reject);if(body)req.write(body);req.end()})}

test('monitor API is protected by a dedicated operator token',async()=>{const manager=fakeManager(),old=process.env.MONITOR_ACCESS_TOKEN;process.env.MONITOR_ACCESS_TOKEN='monitor-secret';try{await withServer(manager,async port=>{let r=await request(port,{path:'/api/monitors'});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'MONITOR_ACCESS_DENIED');r=await request(port,{path:'/api/monitors',headers:{'x-monitor-access-token':'monitor-secret'}});assert.equal(r.status,200);const j=JSON.parse(r.body);assert.equal(j.monitors.length,1);assert.equal(j.monitoring.schedulerEnabled,true)})}finally{if(old===undefined)delete process.env.MONITOR_ACCESS_TOKEN;else process.env.MONITOR_ACCESS_TOKEN=old}});

test('monitor mutation endpoints use JSON and run jobs asynchronously',async()=>{const manager=fakeManager(),old=process.env.MONITOR_ACCESS_TOKEN;process.env.MONITOR_ACCESS_TOKEN='monitor-secret';const headers={'content-type':'application/json','x-monitor-access-token':'monitor-secret'};try{await withServer(manager,async port=>{let r=await request(port,{method:'POST',path:'/api/monitors/upsert',headers,body:JSON.stringify({channel:'@new',intervalMinutes:60,language:'en'})});assert.equal(r.status,200);r=await request(port,{method:'POST',path:'/api/monitors/run',headers,body:JSON.stringify({id:'12345678-abcd'})});assert.equal(r.status,202);await new Promise(r=>setTimeout(r,0));assert.ok(manager.calls.some(c=>c[0]==='run'));r=await request(port,{method:'POST',path:'/api/monitors/enabled',headers,body:JSON.stringify({id:'12345678-abcd',enabled:false})});assert.equal(r.status,200);r=await request(port,{method:'POST',path:'/api/monitors/delete',headers,body:JSON.stringify({id:'12345678-abcd'})});assert.equal(r.status,200)})}finally{if(old===undefined)delete process.env.MONITOR_ACCESS_TOKEN;else process.env.MONITOR_ACCESS_TOKEN=old}});

test('monitor snapshot endpoint streams NDJSON only with operator access',async()=>{const manager=fakeManager(),old=process.env.MONITOR_ACCESS_TOKEN;process.env.MONITOR_ACCESS_TOKEN='monitor-secret';try{await withServer(manager,async port=>{const r=await request(port,{path:'/api/monitors/snapshot?id=12345678-abcd',headers:{'x-monitor-access-token':'monitor-secret'}});assert.equal(r.status,200);assert.match(r.headers['content-type'],/application\/x-ndjson/);assert.match(r.body,/monitor-snapshot/);assert.match(r.body,/"type":"end"/)})}finally{if(old===undefined)delete process.env.MONITOR_ACCESS_TOKEN;else process.env.MONITOR_ACCESS_TOKEN=old}});

test('hosted mode does not grant monitor administration merely because the reverse proxy connects over loopback',async()=>{const manager=fakeManager(),oldNode=process.env.NODE_ENV,oldToken=process.env.MONITOR_ACCESS_TOKEN;process.env.NODE_ENV='production';delete process.env.MONITOR_ACCESS_TOKEN;try{await withServer(manager,async port=>{const r=await request(port,{path:'/api/monitors'});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'MONITOR_ACCESS_DENIED')})}finally{if(oldNode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=oldNode;if(oldToken===undefined)delete process.env.MONITOR_ACCESS_TOKEN;else process.env.MONITOR_ACCESS_TOKEN=oldToken}});
