import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { MonitorManager } from '../lib/monitoring.js';
import { YoutubeError } from '../lib/youtube.js';
import { sha256 } from '../lib/util.js';

const ids=['aaaaaaaaaaa','bbbbbbbbbbb','ccccccccccc','ddddddddddd','eeeeeeeeeee','fffffffffff'];
function discovery(videoIds=ids.slice(0,2)){return{channel:{id:'UCfixture123',title:'Fixture Channel',url:'https://www.youtube.com/@fixture',subscribers:'1.2K',verified:true},videos:videoIds.map((id,i)=>({id,title:`Video ${i+1}`,published:`2026-09-0${Math.min(9,i+1)}`,duration:'10:00',views:String(100+i),kind:'video'})),truncated:false}}
function transcript(id){return{videoId:id,language:'en',languageName:'English',generated:false,source:'fixture',trackName:'fixture',text:`Transcript for ${id}`,segments:[{startMs:0,durationMs:1000,text:`Transcript for ${id}`}],words:3,retrievedAt:new Date().toISOString()}}

async function collect(gen){const out=[];for await(const line of gen)out.push(line);return out}

test('monitor persists configuration and normalizes interrupted state after restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));const m1=new MonitorManager({dataDir:dir,discover:async()=>discovery(),transcript:async id=>transcript(id),schedulerEnabled:false});const created=await m1.upsert({channel:'https://youtube.com/@fixture',language:'en',intervalMinutes:360});assert.equal(created.intervalMinutes,360);m1.state.monitors[0].status='running';await m1['#save']?.(); // private methods are not callable; persist by public toggle below
// Persist a synthetic interrupted state directly to exercise restart recovery.
const statePath=join(dir,'monitors.json');const raw=JSON.parse(await readFile(statePath,'utf8'));raw.monitors[0].status='running';await writeFile(statePath,JSON.stringify(raw));const m2=new MonitorManager({dataDir:dir,discover:async()=>discovery(),transcript:async id=>transcript(id),schedulerEnabled:false});const [loaded]=await m2.list();assert.equal(loaded.status,'interrupted');assert.match(loaded.lastError,/Previous process stopped/);assert.equal(loaded.channel,'https://www.youtube.com/@fixture/videos')});

test('monitor incrementally captures only new videos and emits an integrity-chained snapshot',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let catalog=ids.slice(0,2),calls=[];const manager=new MonitorManager({dataDir:dir,discover:async()=>discovery(catalog),transcript:async id=>{calls.push(id);return transcript(id)},schedulerEnabled:false,captionConcurrency:1});const mon=await manager.upsert({channel:'https://youtube.com/@fixture',intervalMinutes:60});let result=await manager.runNow(mon.id);assert.equal(result.generation,1);assert.equal(result.readyCount,2);assert.deepEqual(calls,ids.slice(0,2));catalog=ids.slice(0,3);calls=[];result=await manager.runNow(mon.id);assert.equal(result.generation,2);assert.equal(result.readyCount,3);assert.equal(result.lastNewCount,1);assert.deepEqual(calls,[ids[2]]);
const lines=await collect(manager.snapshotLines(mon.id));assert.equal(lines.length,6);let chain='0'.repeat(64);for(const raw of lines.slice(0,-1)){const line=raw.trim();chain=sha256(`${chain}:${line}`)}const footer=JSON.parse(lines.at(-1));assert.equal(footer.type,'end');assert.equal(footer.videos,3);assert.equal(footer.generation,2);assert.equal(footer.chain,chain)});

test('monitor reuses an orphan per-video checkpoint after an interrupted generation',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let calls=0;const manager=new MonitorManager({dataDir:dir,discover:async()=>discovery([ids[0]]),transcript:async id=>{calls++;return transcript(id)},schedulerEnabled:false,captionConcurrency:1});const mon=await manager.upsert({channel:'https://youtube.com/@fixture'});const videoDir=join(dir,'sources',mon.id,'videos');await mkdir(videoDir,{recursive:true});const t=transcript(ids[0]),record={schema:1,id:ids[0],integrityHash:sha256(t.text),retrievedAt:new Date().toISOString(),transcript:t};await writeFile(join(videoDir,`${ids[0]}.json`),JSON.stringify(record));const result=await manager.runNow(mon.id);assert.equal(calls,0);assert.equal(result.readyCount,1);assert.equal(result.lastNewCount,1);assert.equal(result.generation,1)});

test('monitor circuit breaker preserves the last completed snapshot',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let phase=1;const manager=new MonitorManager({dataDir:dir,discover:async()=>phase===1?discovery([ids[0]]):discovery(ids),transcript:async id=>{if(phase===1)return transcript(id);throw new YoutubeError('fixture upstream failure','YOUTUBE_NETWORK_BLOCKED',503)},schedulerEnabled:false,captionConcurrency:1});const mon=await manager.upsert({channel:'https://youtube.com/@fixture'});await manager.runNow(mon.id);const before=JSON.parse(await readFile(join(dir,'sources',mon.id,'index.json'),'utf8'));phase=2;await assert.rejects(()=>manager.runNow(mon.id),e=>e.code==='MONITOR_CIRCUIT_OPEN');const after=JSON.parse(await readFile(join(dir,'sources',mon.id,'index.json'),'utf8'));assert.equal(after.generation,before.generation);const current=await manager.get(mon.id);assert.equal(current.status,'failed');assert.match(current.lastError,/circuit breaker/i)});

test('monitor validates channel/language and does not delete a running monitor',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));const manager=new MonitorManager({dataDir:dir,discover:async()=>new Promise(r=>setTimeout(()=>r(discovery([ids[0]])),25)),transcript:async id=>transcript(id),schedulerEnabled:false});await assert.rejects(()=>manager.upsert({channel:'https://example.com/nope'}),e=>e.code==='INVALID_CHANNEL');await assert.rejects(()=>manager.upsert({channel:'@fixture',language:'not valid!'}),e=>e.code==='INVALID_LANGUAGE');const mon=await manager.upsert({channel:'@fixture'});const running=manager.runNow(mon.id);await new Promise(r=>setTimeout(r,5));await assert.rejects(()=>manager.remove(mon.id),e=>e.code==='MONITOR_RUNNING');await running});

test('enabled scheduler runs a due monitor without an open browser request',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let calls=0;const manager=new MonitorManager({dataDir:dir,discover:async()=>{calls++;return discovery([ids[0]])},transcript:async id=>transcript(id),schedulerEnabled:true,pollSeconds:3600,captionConcurrency:1});const mon=await manager.upsert({channel:'youtube.com/@fixture',intervalMinutes:60});manager.startScheduler();for(let i=0;i<40;i++){const cur=await manager.get(mon.id);if(cur?.status==='success')break;await new Promise(r=>setTimeout(r,5))}manager.stopScheduler();const done=await manager.get(mon.id);assert.equal(done.status,'success');assert.equal(done.generation,1);assert.equal(calls,1)});

test('snapshot source metadata is generation-consistent with the atomic index',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));const manager=new MonitorManager({dataDir:dir,discover:async()=>discovery([ids[0]]),transcript:async id=>transcript(id),schedulerEnabled:false});const mon=await manager.upsert({channel:'@fixture'});await manager.runNow(mon.id);const sourcePath=join(dir,'sources',mon.id,'source.json');const bad=JSON.parse(await readFile(sourcePath,'utf8'));bad.title='Mismatched partial write';bad.generation=999;await writeFile(sourcePath,JSON.stringify(bad));const lines=await collect(manager.snapshotLines(mon.id));const sourceRecord=JSON.parse(lines[1]);assert.equal(sourceRecord.source.title,'Fixture Channel');assert.equal(sourceRecord.source.generation,1)});

test('adding a monitor nudges an already-running scheduler immediately',async()=>{const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let calls=0;const manager=new MonitorManager({dataDir:dir,discover:async()=>{calls++;return discovery([ids[0]])},transcript:async id=>transcript(id),schedulerEnabled:true,pollSeconds:3600,captionConcurrency:1});manager.startScheduler();const mon=await manager.upsert({channel:'@fixture',intervalMinutes:60});for(let i=0;i<40;i++){const cur=await manager.get(mon.id);if(cur?.status==='success')break;await new Promise(r=>setTimeout(r,5))}manager.stopScheduler();assert.equal((await manager.get(mon.id)).status,'success');assert.equal(calls,1)});


test('monitor preserves two-point public view and subscriber observations across generations',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let round=0;
  const discover=async()=>{round++;return{channel:{id:'UCfixture123',title:'Fixture Channel',url:'https://www.youtube.com/@fixture',subscribers:round===1?'1.2K':'1.3K',verified:true},videos:[{id:ids[0],title:'Observed Video',published:'2026-09-01',duration:'10:00',views:round===1?'1000':'1250',kind:'video'}],truncated:false}};
  const manager=new MonitorManager({dataDir:dir,discover,transcript:async id=>transcript(id),schedulerEnabled:false,captionConcurrency:1});const mon=await manager.upsert({channel:'@fixture'});await manager.runNow(mon.id);await manager.runNow(mon.id);
  const index=JSON.parse(await readFile(join(dir,'sources',mon.id,'index.json'),'utf8')),v=index.videos[0];
  assert.equal(v.views,'1250');assert.equal(v.previousViews,'1000');assert.ok(v.viewsObservedAt);assert.ok(v.previousViewsObservedAt);assert.equal(index.source.subscribers,'1.3K');assert.equal(index.source.previousSubscribers,'1.2K');assert.ok(index.source.subscribersObservedAt);assert.ok(index.source.previousSubscribersObservedAt);
  const lines=await collect(manager.snapshotLines(mon.id)),source=JSON.parse(lines[1]).source,video=JSON.parse(lines[2]).video;assert.equal(source.previousSubscribers,'1.2K');assert.equal(video.previousViews,'1000');
});

test('scheduler rechecks newly added monitors after a busy tick instead of waiting for the next poll',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let releaseFirst,firstStarted=false;const gate=new Promise(r=>{releaseFirst=r});
  const discover=async channel=>{if(channel.includes('@first')){firstStarted=true;await gate;return{channel:{id:'UCfirst123',title:'First',url:'https://www.youtube.com/@first'},videos:[{id:ids[0],title:'First',views:'10'}],truncated:false}}return{channel:{id:'UCsecond123',title:'Second',url:'https://www.youtube.com/@second'},videos:[{id:ids[1],title:'Second',views:'20'}],truncated:false}};
  const manager=new MonitorManager({dataDir:dir,discover,transcript:async id=>transcript(id),schedulerEnabled:true,pollSeconds:3600,captionConcurrency:1,jobConcurrency:1});manager.startScheduler();const first=await manager.upsert({channel:'@first'});for(let i=0;i<40&&!firstStarted;i++)await new Promise(r=>setTimeout(r,5));assert.equal(firstStarted,true);const second=await manager.upsert({channel:'@second'});releaseFirst();for(let i=0;i<80;i++){if((await manager.get(first.id))?.status==='success'&&(await manager.get(second.id))?.status==='success')break;await new Promise(r=>setTimeout(r,5))}manager.stopScheduler();assert.equal((await manager.get(first.id)).status,'success');assert.equal((await manager.get(second.id)).status,'success')});

test('scheduler bounds parallel channel jobs with MONITOR_JOB_CONCURRENCY semantics',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'yke-monitor-'));let active=0,peak=0;const discover=async channel=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,20));active--;const second=channel.includes('@two');return{channel:{id:second?'UCtwo123':'UCone123',title:second?'Two':'One',url:second?'https://www.youtube.com/@two':'https://www.youtube.com/@one'},videos:[{id:second?ids[1]:ids[0],title:'V',views:'10'}],truncated:false}};
  const manager=new MonitorManager({dataDir:dir,discover,transcript:async id=>transcript(id),schedulerEnabled:false,pollSeconds:3600,captionConcurrency:1,jobConcurrency:2});const one=await manager.upsert({channel:'@one'}),two=await manager.upsert({channel:'@two'});manager.schedulerEnabled=true;manager.startScheduler();for(let i=0;i<80;i++){if((await manager.get(one.id))?.status==='success'&&(await manager.get(two.id))?.status==='success')break;await new Promise(r=>setTimeout(r,5))}manager.stopScheduler();assert.equal(peak,2);assert.equal(manager.status().jobConcurrency,2)});
