import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
test('v2.3 ships background monitor controls and offline module packaging',async()=>{const html=await readFile(new URL('public/index.html',root),'utf8'),sw=await readFile(new URL('public/sw.js',root),'utf8'),monitor=await readFile(new URL('public/monitor.js',root),'utf8');for(const id of ['monitorChannelInput','monitorInterval','monitorLanguage','monitorCollection','monitorTokenInput','monitorAdd','monitorRefresh','monitorStatus','monitorList'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/src="\/monitor\.js"/);assert.match(sw,/'\/monitor\.js'/);assert.match(monitor,/x-monitor-access-token/);assert.match(monitor,/\/api\/monitors\/snapshot/)});
test('monitor token is session-only and monitor import shares the knowledge-base mutation lock',async()=>{const monitor=await readFile(new URL('public/monitor.js',root),'utf8');assert.match(monitor,/type="password"|monitorTokenInput/);assert.doesNotMatch(monitor,/localStorage\.setItem\([^\n]*monitor.*token/i);assert.match(monitor,/yke-kb-mutation-lock/);assert.match(monitor,/kb_staging/);assert.match(monitor,/transaction\(\['kb_videos','kb_sources','kb_meta','kb_staging'\],'readwrite'\)/);assert.match(monitor,/footer\.chain!==chain/);assert.match(monitor,/Transcript integrity failed/)});
test('monitor generation provenance survives normal knowledge-base backups',async()=>{const kb=await readFile(new URL('public/kb.js',root),'utf8');assert.match(kb,/monitorId:String\(s\?\.monitorId/);assert.match(kb,/monitorGeneration:Math\.max/);assert.match(kb,/type:'source',source:s/)});
test('monitor deployment defaults are opt-in, protected, and persistent-volume aware',async()=>{const env=await readFile(new URL('.env.example',root),'utf8'),docker=await readFile(new URL('Dockerfile',root),'utf8'),security=await readFile(new URL('SECURITY.md',root),'utf8'),privacy=await readFile(new URL('PRIVACY.md',root),'utf8');assert.match(env,/MONITORING_ENABLED=false/);assert.match(env,/MONITOR_ACCESS_TOKEN/);assert.match(env,/MONITOR_DATA_DIR/);assert.match(docker,/MONITOR_DATA_DIR=\/data\/monitoring/);assert.match(docker,/VOLUME \["\/data"\]/);assert.match(security,/Background-monitor security/);assert.match(privacy,/Background monitoring/)});


test('monitor refresh preserves the prior derived analysis so v2.4 can compute longitudinal changes',async()=>{const monitor=await readFile(new URL('public/monitor.js',root),'utf8');assert.doesNotMatch(monitor,/meta\.delete\(`analysis:\$\{source\.id\}`\)/);assert.match(monitor,/sources\.put\(source\);stage\.clear\(\);resolve\(\)/)});
