import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
test('release versions stay aligned',async()=>{const pkg=JSON.parse(await readFile(new URL('package.json',root),'utf8'));const lock=JSON.parse(await readFile(new URL('package-lock.json',root),'utf8'));assert.equal(lock.version,pkg.version);assert.equal(lock.packages?.['']?.version,pkg.version);const server=await readFile(new URL('server.js',root),'utf8');const sw=await readFile(new URL('public/sw.js',root),'utf8');const app=await readFile(new URL('public/app.js',root),'utf8');const kb=await readFile(new URL('public/kb.js',root),'utf8');const tauri=JSON.parse(await readFile(new URL('src-tauri/tauri.conf.json',root),'utf8'));const v=pkg.version.replaceAll('.','\\.');assert.match(server,new RegExp(`VERSION='${v}'`));assert.match(sw,new RegExp(`cts-v${v}`));assert.match(app,new RegExp(`appVersion:'${v}'`));assert.match(app,new RegExp(`version:'${v}'`));assert.match(kb,new RegExp(`appVersion:'${v}'`));assert.equal(tauri.version,pkg.version)});
test('IndexedDB schema version is shared by app and search worker',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');const worker=await readFile(new URL('public/search-worker.js',root),'utf8');const kb=await readFile(new URL('public/kb.js',root),'utf8');const a=Number(app.match(/const DB_VERSION=(\d+)/)?.[1]);const b=Number(worker.match(/const DB_VERSION=(\d+)/)?.[1]);const c=Number(kb.match(/const DB_VERSION=(\d+)/)?.[1]);assert.equal(a,b);assert.equal(a,c);assert.ok(a>=10)});
test('paid AI is a separate browser endpoint and is never retried',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(app,/\/api\/transcribe/);assert.doesNotMatch(app,/accessToken:els\.aiTokenInput/);assert.match(app,/x-ai-access-token/);assert.match(app,/\/api\/transcribe[^\n]+retries:0/)});
test('service worker never caches API traffic',async()=>{const sw=await readFile(new URL('public/sw.js',root),'utf8');assert.match(sw,/startsWith\('\/api\/'\)/)});

test('Docker uses a reproducibly pinned extractor and supported JS runtime',async()=>{const docker=await readFile(new URL('Dockerfile',root),'utf8');const youtube=await readFile(new URL('lib/youtube.js',root),'utf8');const ai=await readFile(new URL('lib/ai-transcription.js',root),'utf8');assert.match(docker,/FROM node:22-/);const pin=docker.match(/ARG YTDLP_VERSION=(\d{4}\.\d{1,2}\.\d{1,2}(?:\.\d+)?)/)?.[1];assert.ok(pin,'yt-dlp must be pinned to an explicit stable release');assert.doesNotMatch(pin,/latest|nightly/i);assert.match(docker,/yt-dlp\[default\]==\$\{YTDLP_VERSION\}/);assert.match(youtube,/--ignore-config/);assert.match(youtube,/--js-runtimes/);assert.match(youtube,/process\.execPath/);assert.match(ai,/--ignore-config/);assert.match(ai,/--js-runtimes/);assert.match(ai,/process\.execPath/)});
test('backup restore is staged, counted, sanitized, and atomically committed',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(app,/schema:3/);assert.match(app,/footerChain!==chain/);assert.match(app,/type:'end',count/);assert.match(app,/sanitizeImportedVideo/);assert.match(app,/commitStaging\(meta\)/);assert.match(app,/transaction\(\['videos','meta','staging'\],'readwrite'\)/)});
test('quality filter remains wired through UI and search worker',async()=>{const html=await readFile(new URL('public/index.html',root),'utf8');const app=await readFile(new URL('public/app.js',root),'utf8');const worker=await readFile(new URL('public/search-worker.js',root),'utf8');assert.match(html,/id="qualityFilter"/);assert.match(app,/quality:els\.qualityFilter\.value/);assert.match(worker,/f\.quality/)});

test('paid AI bulk fill requires a distinct confirmed UI path',async()=>{const html=await readFile(new URL('public/index.html',root),'utf8');const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(html,/id="aiFillButton"/);assert.match(app,/aiMissing:true/);assert.match(app,/Paid AI fill may submit every no-caption\/failed video/);assert.match(app,/if\(err\.code==='NO_CAPTIONS'&&allowAi\)/);assert.doesNotMatch(app,/NO_CAPTIONS'&&els\.aiFallbackInput\.checked/)});
test('service worker handles only same-origin non-API GETs',async()=>{const sw=await readFile(new URL('public/sw.js',root),'utf8');assert.match(sw,/u\.origin!==self\.location\.origin/);assert.match(sw,/r\.ok&&r\.type==='basic'/)});
test('large-run UI uses incremental metrics and throttled renders',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(app,/function metricPart/);assert.match(app,/function metricApply/);assert.match(app,/function scheduleRender/);assert.match(app,/state\.running\?1000:50/)});
test('single-library guard and truncation warning are present',async()=>{const html=await readFile(new URL('public/index.html',root),'utf8');const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(html,/id="catalogWarning"/);assert.match(app,/sameChannel\(state\.meta\.channel,result\.channel\)/);assert.match(app,/50,000-item safety limit/)});
test('catalog refresh stages discovery before atomic archive-state commit',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(app,/stageDiscoveryBatch\(items,refreshToken\)/);assert.match(app,/finalizeDiscovery\(refreshToken,meta\)/);assert.match(app,/transaction\(\['videos','meta'\],'readwrite'\)/);assert.match(app,/v\.archived=v\._refreshToken!==refreshToken/);assert.match(app,/cleanupDiscoveryStage\(refreshToken\)/);assert.doesNotMatch(app,/async function markAllArchived/) });
test('release docs and browser branding match package version',async()=>{const pkg=JSON.parse(await readFile(new URL('package.json',root),'utf8'));const readme=await readFile(new URL('README.md',root),'utf8');const changelog=await readFile(new URL('CHANGELOG.md',root),'utf8');const html=await readFile(new URL('public/index.html',root),'utf8');const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(readme,new RegExp(`v${pkg.version.replaceAll('.','\\.')}`));assert.match(changelog,new RegExp(`## ${pkg.version.replaceAll('.','\\.')}`));assert.match(html,new RegExp(`v${pkg.version.split('.').slice(0,2).join('\\.')}`));assert.match(app,new RegExp(`appVersion:'${pkg.version.replaceAll('.','\\.')}'`))});
test('public discovery remains credential-free and operator docs are shipped',async()=>{const html=await readFile(new URL('public/index.html',root),'utf8');const server=await readFile(new URL('server.js',root),'utf8');const env=await readFile(new URL('.env.example',root),'utf8');const security=await readFile(new URL('SECURITY.md',root),'utf8');const privacy=await readFile(new URL('PRIVACY.md',root),'utf8');assert.doesNotMatch(html,/youtubeApi|apiKeyInput|Data API key/i);assert.match(server,/YOUTUBE_DATA_API_DISABLED/);assert.doesNotMatch(env,/YOUTUBE_API_KEY=/);assert.match(security,/AI_ACCESS_TOKEN/);assert.match(privacy,/IndexedDB/)});
test('CI covers supported Node releases and builds the production container',async()=>{const ci=await readFile(new URL('.github/workflows/ci.yml',root),'utf8');const docker=await readFile(new URL('Dockerfile',root),'utf8');assert.match(ci,/node: \[22, 24\]/);assert.match(ci,/docker\/build-push-action@v6/);assert.match(docker,/STOPSIGNAL SIGTERM/);assert.match(docker,/PYTHONDONTWRITEBYTECODE=1/)});
test('bulk capture has an upstream failure circuit breaker',async()=>{const app=await readFile(new URL('public/app.js',root),'utf8');assert.match(app,/transientFailureStreak/);assert.match(app,/YOUTUBE_NETWORK_BLOCKED/);assert.match(app,/YOUTUBE_BLOCKED/);assert.match(app,/UPSTREAM_CIRCUIT_OPEN/);assert.match(app,/five consecutive upstream\/network failures/)});
test('CSP explicitly constrains workers and manifests',async()=>{const security=await readFile(new URL('lib/security.js',root),'utf8');assert.match(security,/worker-src 'self'/);assert.match(security,/manifest-src 'self'/);assert.match(security,/origin-agent-cluster/)});
test('desktop release keeps the sidecar private and native recovery bounded',async()=>{const [rust,cfgText,caps,desktop,store,ci]=await Promise.all([readFile(new URL('src-tauri/src/main.rs',root),'utf8'),readFile(new URL('src-tauri/tauri.conf.json',root),'utf8'),readFile(new URL('src-tauri/capabilities/default.json',root),'utf8'),readFile(new URL('public/desktop.js',root),'utf8'),readFile(new URL('lib/desktop-store.js',root),'utf8'),readFile(new URL('.github/workflows/ci.yml',root),'utf8')]);const cfg=JSON.parse(cfgText);assert.deepEqual(cfg.bundle.externalBin,['binaries/yke-node']);assert.match(rust,/TcpListener::bind\("127\.0\.0\.1:0"\)/);assert.match(rust,/DESKTOP_SESSION_TOKEN/);assert.match(rust,/sample_iter\(&Alphanumeric\)\.take\(48\)/);assert.match(rust,/MONITORING_ENABLED","1"/);assert.doesNotMatch(caps,/shell:allow-spawn|shell:allow-execute/);assert.doesNotMatch(caps,/\"main\"/);assert.match(caps,/\"settings\"/);assert.match(desktop,/STORES=\['kb_sources','kb_videos','kb_meta'\]/);assert.match(desktop,/Reload browser cache from SQLite/);assert.match(desktop,/api\/desktop\/mirror\/records/);assert.match(desktop,/kb_staging/);assert.match(desktop,/Existing browser cache was not changed/);assert.match(store,/records\.length>100/);assert.match(store,/MAX_RECORD_BYTES=25\*1024\*1024/);assert.match(ci,/desktop-check:/);assert.match(ci,/windows-latest, macos-latest, ubuntu-22\.04/);assert.match(ci,/cargo check --manifest-path src-tauri\/Cargo\.toml/)});
