import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import { createServer, VERSION } from '../server.js';

async function withServer(fn){const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const {port}=server.address();try{return await fn(port)}finally{await new Promise(r=>server.close(r))}}
function rawRequest(port,{method='GET',path='/',headers={},body=''}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,method,path,headers:{Host:'localhost',...headers}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks).toString()}))});req.on('error',reject);if(body)req.write(body);req.end()})}

test('health endpoint exposes release and hardening headers',()=>withServer(async port=>{const r=await rawRequest(port,{path:'/api/health'});assert.equal(r.status,200);const j=JSON.parse(r.body);assert.equal(j.version,VERSION);assert.match(r.headers['content-security-policy'],/frame-ancestors 'none'/);assert.equal(r.headers['x-frame-options'],'DENY');assert.match(r.headers['x-request-id'],/^[0-9a-f-]{36}$/i);assert.match(r.headers['server-timing'],/^app;dur=\d+/)}));
test('serves app shell and service worker',()=>withServer(async port=>{const shell=await rawRequest(port,{path:'/'});assert.equal(shell.status,200);assert.match(shell.body,/YouTube Knowledge Engine/);const sw=await rawRequest(port,{path:'/sw.js'});assert.equal(sw.status,200);assert.match(sw.body,new RegExp(`cts-v${VERSION.replaceAll('.','\\.')}`))}));
test('rejects POST without application/json',()=>withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{'content-type':'text/plain'},body:'{}'});assert.equal(r.status,415);assert.equal(JSON.parse(r.body).code,'UNSUPPORTED_MEDIA_TYPE')}));
test('rejects cross-site POSTs before expensive work',()=>withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{'content-type':'application/json','sec-fetch-site':'cross-site','origin':'https://evil.example'},body:'{}'});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'CROSS_SITE_BLOCKED')}));

test('rejects a different localhost Origin port',()=>withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{Host:`localhost:${port}`,'content-type':'application/json','origin':`http://localhost:${port+1}`,'sec-fetch-site':'same-site'},body:JSON.stringify({videoId:'bad'})});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'CROSS_ORIGIN_BLOCKED')}));

test('accepts bracketed IPv6 localhost Host syntax at the host-validation layer',()=>withServer(async port=>{const r=await rawRequest(port,{path:'/api/health',headers:{Host:`[::1]:${port}`}});assert.equal(r.status,200)}));
test('rejects invalid video IDs without touching YouTube',()=>withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{'content-type':'application/json'},body:JSON.stringify({videoId:'bad'})});assert.equal(r.status,400);assert.equal(JSON.parse(r.body).code,'INVALID_VIDEO_ID')}));
test('local server rejects DNS-rebinding Host header',()=>withServer(async port=>{const r=await rawRequest(port,{path:'/api/health',headers:{Host:'attacker.example'}});assert.equal(r.status,421);assert.equal(JSON.parse(r.body).code,'BAD_HOST')}));

test('rejects oversized JSON request bodies',()=>withServer(async port=>{const body=JSON.stringify({videoId:'abcdefghijk',padding:'x'.repeat(300000)});const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{'content-type':'application/json','content-length':Buffer.byteLength(body)},body});assert.equal(r.status,413);assert.equal(JSON.parse(r.body).code,'BODY_TOO_LARGE')}));

test('same-origin JSON POST reaches validation normally',()=>withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/transcript',headers:{'content-type':'application/json','origin':`http://localhost`,'sec-fetch-site':'same-origin'},body:JSON.stringify({videoId:'bad'})});assert.equal(r.status,400);assert.equal(JSON.parse(r.body).code,'INVALID_VIDEO_ID')}));

test('AI access token protects paid endpoint even on loopback',()=>withServer(async port=>{const old=process.env.AI_ACCESS_TOKEN;process.env.AI_ACCESS_TOKEN='secret-value';try{const r=await rawRequest(port,{method:'POST',path:'/api/transcribe',headers:{'content-type':'application/json'},body:JSON.stringify({videoId:'abcdefghijk'})});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'AI_ACCESS_DENIED')}finally{if(old===undefined)delete process.env.AI_ACCESS_TOKEN;else process.env.AI_ACCESS_TOKEN=old}}));

test('discovery rejects empty channels and legacy Data API keys before network work',()=>withServer(async port=>{let r=await rawRequest(port,{method:'POST',path:'/api/discover',headers:{'content-type':'application/json'},body:JSON.stringify({channel:''})});assert.equal(r.status,400);assert.equal(JSON.parse(r.body).code,'INVALID_CHANNEL');r=await rawRequest(port,{method:'POST',path:'/api/discover',headers:{'content-type':'application/json'},body:JSON.stringify({channel:'@fixture',apiKey:'legacy-key'})});assert.equal(r.status,400);assert.equal(JSON.parse(r.body).code,'YOUTUBE_DATA_API_DISABLED')}));

test('production loopback does not bypass paid-AI authentication',()=>withServer(async port=>{const oldNode=process.env.NODE_ENV,oldToken=process.env.AI_ACCESS_TOKEN,oldPublic=process.env.AI_PUBLIC_FALLBACK,oldProxy=process.env.TRUST_PROXY;delete process.env.AI_ACCESS_TOKEN;delete process.env.AI_PUBLIC_FALLBACK;delete process.env.TRUST_PROXY;process.env.NODE_ENV='production';try{const r=await rawRequest(port,{method:'POST',path:'/api/transcribe',headers:{'content-type':'application/json'},body:JSON.stringify({videoId:'abcdefghijk'})});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'AI_ACCESS_DENIED')}finally{for(const [k,v] of [['NODE_ENV',oldNode],['AI_ACCESS_TOKEN',oldToken],['AI_PUBLIC_FALLBACK',oldPublic],['TRUST_PROXY',oldProxy]]){if(v===undefined)delete process.env[k];else process.env[k]=v}}}));

test('server applies bounded header/request and keepalive limits',()=>{const server=createServer();try{assert.equal(server.headersTimeout,15000);assert.equal(server.requestTimeout,30000);assert.equal(server.keepAliveTimeout,5000);assert.equal(server.maxRequestsPerSocket,100);assert.equal(server.maxHeadersCount,100);assert.ok(server.maxConnections>=10)}finally{server.close()}});


test('semantic embedding endpoint is protected by the paid-AI access gate',()=>withServer(async port=>{const old=process.env.AI_ACCESS_TOKEN;process.env.AI_ACCESS_TOKEN='embedding-secret';try{const r=await rawRequest(port,{method:'POST',path:'/api/embeddings',headers:{'content-type':'application/json'},body:JSON.stringify({texts:['risk management']})});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'AI_ACCESS_DENIED')}finally{if(old===undefined)delete process.env.AI_ACCESS_TOKEN;else process.env.AI_ACCESS_TOKEN=old}}));

test('health advertises embedding capability separately from research synthesis',()=>withServer(async port=>{const r=await rawRequest(port,{path:'/api/health'});const j=JSON.parse(r.body);assert.equal(typeof j.embeddingsConfigured,'boolean');assert.ok(j.embedding&&Object.hasOwn(j.embedding,'providerId'));assert.ok(j.cache&&j.cache.embeddings)}));

test('embedding gateway validates and normalizes an OpenAI-compatible provider response',async()=>{const provider=http.createServer((req,res)=>{const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>{const body=JSON.parse(Buffer.concat(chunks).toString());assert.equal(body.model,'fixture-embed');assert.deepEqual(body.input,['alpha','beta']);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({data:[{index:1,embedding:[0,5]},{index:0,embedding:[3,4]}]}))})});await new Promise(r=>provider.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${provider.address().port}/embeddings`;const keys=['EMBEDDING_API_URL','EMBEDDING_API_KEY','EMBEDDING_MODEL','EMBEDDING_AUTH','AI_ACCESS_TOKEN'],old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));Object.assign(process.env,{EMBEDDING_API_URL:url,EMBEDDING_API_KEY:'provider-secret',EMBEDDING_MODEL:'fixture-embed',EMBEDDING_AUTH:'bearer',AI_ACCESS_TOKEN:'semantic-secret'});try{await withServer(async port=>{const r=await rawRequest(port,{method:'POST',path:'/api/embeddings',headers:{'content-type':'application/json','x-ai-access-token':'semantic-secret'},body:JSON.stringify({texts:['alpha','beta']})});assert.equal(r.status,200);const j=JSON.parse(r.body);assert.equal(j.dimensions,2);assert.deepEqual(j.vectors,[[0.6,0.8],[0,1]]);assert.equal(j.model,'fixture-embed');assert.match(j.providerId,/^[a-f0-9]{24}$/)})}finally{for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k]}await new Promise(r=>provider.close(r))}});


test('public audience comment endpoint validates, bounds and caches sampled comments',async()=>{let calls=0;const commentFetcher=async(videoId,{maxComments,sort})=>{calls++;assert.equal(videoId,'abcdefghijk');assert.equal(maxComments,200);assert.equal(sort,'top');return{videoId,title:'Fixture',commentCount:2,source:'fixture',retrievedAt:'2026-09-06T00:00:00Z',comments:[{commentId:'c1',text:'Useful',likeCount:1,timestamp:null,parent:'root',authorIsUploader:false}]}};const server=createServer({commentFetcher});await new Promise(r=>server.listen(0,'127.0.0.1',r));const {port}=server.address();try{const headers={'content-type':'application/json'};let r=await rawRequest(port,{method:'POST',path:'/api/comments',headers,body:JSON.stringify({videoId:'bad'})});assert.equal(r.status,400);assert.equal(JSON.parse(r.body).code,'INVALID_VIDEO_ID');r=await rawRequest(port,{method:'POST',path:'/api/comments',headers,body:JSON.stringify({videoId:'abcdefghijk',maxComments:999,sort:'other'})});assert.equal(r.status,200);let j=JSON.parse(r.body);assert.equal(j.comments.length,1);assert.equal(j.cached,false);r=await rawRequest(port,{method:'POST',path:'/api/comments',headers,body:JSON.stringify({videoId:'abcdefghijk',maxComments:999,sort:'other'})});j=JSON.parse(r.body);assert.equal(j.cached,true);assert.equal(calls,1)}finally{await new Promise(r=>server.close(r))}});
