import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { analyzeVideoVisuals, sanitizeVisualResult, visualProviderInfo } from '../lib/visual-ai.js';
import { prioritizeVisualEvents, selectVisualCandidates, summarizeVisualCorpus, visualTimestampUrl, visualTypeLabel } from '../public/visual-core.js';
import { createServer } from '../server.js';
import { readFile } from 'node:fs/promises';

function withEnv(values,fn){const old={};for(const [k,v] of Object.entries(values)){old[k]=process.env[k];if(v===null)delete process.env[k];else process.env[k]=String(v)}return Promise.resolve().then(fn).finally(()=>{for(const [k,v] of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v}})}
function rawRequest(port,{method='GET',path='/',headers={},body=''}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,method,path,headers:{Host:'localhost',...headers}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks).toString()}))});req.on('error',reject);if(body)req.write(body);req.end()})}
async function withServer(server,fn){await new Promise(r=>server.listen(0,'127.0.0.1',r));try{return await fn(server.address().port)}finally{await new Promise(r=>server.close(r))}}

test('visual result sanitizer bounds and whitelists model output',()=>{const r=sanitizeVisualResult({summary:'  Visible settings  ',visualOnlyFindings:[' x '],potentialConflicts:[' y '],events:[{startMs:-5,endMs:1e12,type:'invented',importance:'urgent',observation:'  RSI settings shown  ',ocrText:' RSI 14 ',values:[{label:'Period',value:'14',unit:''}],relationship:'definitely_wrong',spokenContext:'creator says defaults',reason:'mismatch',confidence:4}]},{videoId:'abcdefghijk',model:'fixture',processing:'agentic'});assert.equal(r.schema,1);assert.equal(r.events.length,1);assert.equal(r.events[0].startMs,0);assert.equal(r.events[0].endMs,604800000);assert.equal(r.events[0].type,'other');assert.equal(r.events[0].importance,'medium');assert.equal(r.events[0].relationship,'uncertain');assert.equal(r.events[0].confidence,1);assert.deepEqual(r.events[0].values,[{label:'Period',value:'14',unit:''}]);assert.equal(r.summary,'Visible settings')});

test('visual candidate triage prefers videos likely to contain settings/charts',()=>{const report={videoPerformance:[{id:'aaaaaaaaaaa',title:'My trading setup and backtest',performanceIndex:1.2},{id:'bbbbbbbbbbb',title:'Weekly thoughts',performanceIndex:2}],evidence:[{videoId:'aaaaaaaaaaa',category:'strategy_rule'},{videoId:'aaaaaaaaaaa',category:'performance_claim'}],outliers:[],audienceCandidates:[]};const c=selectVisualCandidates(report,2);assert.equal(c[0].id,'aaaaaaaaaaa');assert.ok(c[0].visualScore>c[1].visualScore)});

test('visual corpus summary and priority ordering surface conflicts and visual-only evidence',()=>{const reports=[{events:[{type:'metric',importance:'high',relationship:'potential_conflict',confidence:.8},{type:'settings',importance:'medium',relationship:'visual_only',confidence:.9}]}];const s=summarizeVisualCorpus(reports);assert.deepEqual({videos:s.videos,events:s.events,visualOnly:s.visualOnly,potentialConflicts:s.potentialConflicts,highImportance:s.highImportance},{videos:1,events:2,visualOnly:1,potentialConflicts:1,highImportance:1});assert.equal(prioritizeVisualEvents(reports[0],1)[0].relationship,'potential_conflict');assert.equal(visualTypeLabel('software_ui'),'Software UI');assert.match(visualTimestampUrl('abcdefghijk',61000),/&t=61s$/)});

test('Gemini visual adapter sends a direct public YouTube URI with structured agentic output',async()=>withEnv({VISUAL_PROVIDER:'gemini',VISUAL_GEMINI_API_KEY:'fixture-key',VISUAL_MODEL:'gemini-3.8-flash',VISUAL_PROCESSING:'agentic'},async()=>{const oldFetch=globalThis.fetch;let seen;globalThis.fetch=async(url,opts)=>{seen={url,opts,body:JSON.parse(opts.body)};return new Response(JSON.stringify({id:'interaction-1',status:'completed',steps:[{type:'model_output',content:[{type:'text',text:JSON.stringify({summary:'Saw chart',visualOnlyFindings:['ATR setting shown'],potentialConflicts:[],events:[{startMs:1000,endMs:2000,type:'settings',importance:'high',observation:'ATR length is visibly set to 14',ocrText:'ATR Length 14',values:[{label:'ATR length',value:'14',unit:''}],relationship:'visual_only',spokenContext:'',reason:'Not stated aloud',confidence:.93}]})}]}],usage:{total_input_tokens:100,total_output_tokens:50,total_tokens:150}}),{status:200,headers:{'content-type':'application/json'}})};try{const r=await analyzeVideoVisuals('abcdefghijk',{focus:'settings'});assert.equal(r.events[0].values[0].value,'14');assert.equal(r.usage.totalTokens,150);assert.equal(seen.url,'https://generativelanguage.googleapis.com/v1beta/interactions');assert.equal(seen.opts.headers['x-goog-api-key'],'fixture-key');assert.equal(seen.body.input[0].uri,'https://www.youtube.com/watch?v=abcdefghijk');assert.equal(seen.body.input[0].processing,'agentic');assert.equal(seen.body.store,false);assert.match(seen.body.system_instruction,/untrusted source evidence/);assert.equal(seen.body.response_format.mime_type,'application/json');assert.equal(seen.body.response_format.schema.type,'object')}finally{globalThis.fetch=oldFetch}}));

test('visual adapter rejects invalid IDs before provider work',async()=>{let called=false;const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{called=true};try{await assert.rejects(()=>analyzeVideoVisuals('bad'),e=>e?.code==='INVALID_VIDEO_ID');assert.equal(called,false)}finally{globalThis.fetch=oldFetch}});

test('visual API is AI-gated, bounded, cached, and exposes provider health',async()=>withEnv({AI_ACCESS_TOKEN:'visual-access',VISUAL_PROVIDER:'gemini',VISUAL_GEMINI_API_KEY:'fixture-key',VISUAL_MODEL:'gemini-3.8-flash'},async()=>{let calls=0;const visualAnalyzer=async(videoId,{focus})=>{calls++;assert.equal(videoId,'abcdefghijk');assert.equal(focus.length,600);return{schema:1,videoId,generatedAt:'2026-09-06T00:00:00Z',provider:'fixture',model:'fixture',processing:'agentic',summary:'ok',visualOnlyFindings:[],potentialConflicts:[],events:[]}};const server=createServer({visualAnalyzer});await withServer(server,async port=>{const headers={'content-type':'application/json'},payload=JSON.stringify({videoId:'abcdefghijk',focus:'x'.repeat(1000)});let r=await rawRequest(port,{method:'POST',path:'/api/visual/analyze',headers,body:payload});assert.equal(r.status,403);assert.equal(JSON.parse(r.body).code,'AI_ACCESS_DENIED');r=await rawRequest(port,{method:'POST',path:'/api/visual/analyze',headers:{...headers,'x-ai-access-token':'visual-access'},body:payload});assert.equal(r.status,200);let j=JSON.parse(r.body);assert.equal(j.cached,false);r=await rawRequest(port,{method:'POST',path:'/api/visual/analyze',headers:{...headers,'x-ai-access-token':'visual-access'},body:payload});j=JSON.parse(r.body);assert.equal(j.cached,true);assert.equal(calls,1);const h=JSON.parse((await rawRequest(port,{path:'/api/health'})).body);assert.equal(h.visualConfigured,true);assert.equal(h.visual.model,'gemini-3.8-flash');assert.ok(h.cache.visual)})}));

test('visual provider info never exposes the provider API key',()=>withEnv({VISUAL_PROVIDER:'gemini',VISUAL_GEMINI_API_KEY:'do-not-leak',VISUAL_MODEL:'fixture-model'},async()=>{const info=visualProviderInfo();assert.equal(info.configured,true);assert.equal(JSON.stringify(info).includes('do-not-leak'),false)}));

const root=new URL('../',import.meta.url);
test('v2.6 UI, offline shell and browser code expose visual intelligence without provider secrets',async()=>{const [html,analysis,sw]=await Promise.all([readFile(new URL('public/index.html',root),'utf8'),readFile(new URL('public/analysis.js',root),'utf8'),readFile(new URL('public/sw.js',root),'utf8')]);assert.match(html,/id="analysisVisualRun"/);assert.match(html,/Visual intelligence/);assert.match(analysis,/\/api\/visual\/analyze/);assert.match(analysis,/x-ai-access-token/);assert.doesNotMatch(analysis,/VISUAL_GEMINI_API_KEY/);assert.match(sw,/visual-core\.js/)})
